module.exports = {
  important: true,
  theme: {
    extend: {},
    pseudo: {
      before: 'before',
      after: 'after',
      'not-first': 'not(:first-child)',
    },
    fontFamily: {
      sans: ['IBM Plex Sans', 'sans-serif'],
    },
    borderRadius: {
      none: '0',
      sm: '.125rem',
      default: '.25rem',
      lg: '.5rem',
      full: '9999px',
      large: '12px',
      exlg: '1em',
    },
    borderWidth: {
      default: '1px',
      '0': '0',
      '2': '2px',
      '3': '3px',
      '4': '4px',
      '6': '6px',
      '8': '8px',
    },
    padding: {
      '1p': '1px',
      sm: '8px',
      md: '16px',
      lg: '24px',
      xl: '48px',
    },
    inset: {
      in10: '-10px',
      in15: '-15px',
      in20: '-20px',
      '0': 0,
      '05': '5%',
      '60': '60%',
      '70': '70%',
      '80': '80%',
      '1/10': '10%',
      '2/10': '20%',
      '3/10': '30%',
      '4/10': '40%',
      '1/2': '50%',
    },
  },
  variants: {},
  plugins: [],
};
